spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sboot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: wanglu
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none